parameters:
    app.telegram_bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    app.telegram_webhook_secret: '%env(TELEGRAM_WEBHOOK_SECRET)%'
    app.telegram_bot_username: '%env(TELEGRAM_BOT_USERNAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TelegramBotService:
        arguments:
            $token: '%app.telegram_bot_token%'
            $botUsername: '%app.telegram_bot_username%'
            $telegramLogger: '@monolog.logger.telegram'
            $databaseLogger: '@monolog.logger.database'
            $securityLogger: '@monolog.logger.security'

    App\Command\SetupWebhookCommand:
        arguments:
            $telegramBotToken: '%app.telegram_bot_token%'
            $webhookSecret: '%app.telegram_webhook_secret%'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments'] 